### ISSUE TITLE
SimpleForm.proccessForm can't get data when handling button click event.

### ISSUE THREAD

**Issue by delgermurun** [thespacedojo/simple-form#4]
If I catch 'submit form' event, getting correct data. But If I catch 'click input[type="submit"]' event, then SimpleForm.proccessForm(event.target) returns blank object.

Is it bug or just the way it works?

I saw the code and I think it is jquery bug.

http://jsfiddle.net/jn4td/ It is jquery demo.

**Comment by queso** [comment]
The reason you are having trouble is because event.target in the context of the button is the button itself.  When you catch submit form, the event.target is the form itself, which we call serializeArray on.

Is there a reason you want to catch click on the button instead of submitting the form?  I guess you could use jquery to go up the DOM tree and find the form to pass to:

```
SimpleForm.processForm(jqueryFormDomElement)
```

**Comment by delgermurun** [comment]
Got it :-) I think I was very tired :-D

**Comment by queso** [comment]
No worries, glad to field questions like this, now we have a search history to help people out in the future :)
