### ISSUE TITLE
value="{{var}}"

### ISSUE THREAD

**Issue by stephentcannon** [thespacedojo/simple-form#5]
Cannot get template data context vars into value.  How do you setup edit/update forms then?

**Comment by queso** [comment]
To be clear on this, SimpleForm uses whatever `this` would evaluate to in the context of the template.  It assumes there is a property on the object.  I set it up this way because we use Minimongoid and our ORM objects have the data set as properties on the object.

If you find you need to do something weird, you can always just do:

```
{{#with Object}}

  {{text_field 'objProperty'}}

{{/with}}
```

To help control the context a little more tightly in the template.
